name: Build docker and push to deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version'
        required: true
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Tencent Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: 构建镜像
        run: |
          docker build --file Dockerfile --tag ccr.ccs.tencentyun.com/owenyang/notion-next:${{ github.event.inputs.version }} --tag ccr.ccs.tencentyun.com/owenyang/notion-next:latest .
      - name: 把构建好的镜像推送到腾讯仓库
        run: |
          docker push ccr.ccs.tencentyun.com/owenyang/notion-next:${{ github.event.inputs.version }}
          docker push ccr.ccs.tencentyun.com/owenyang/notion-next:latest
      - 
        name: Status Push
        run: |
          curl https://api.day.app/${{ secrets.PUSH_TOKEN }}/actions:notion-next-blog/✅构建成功-版本${{ github.event.inputs.version }}?icon=https://static.owenyang.top/blogs/avatar.jpg
          # curl https://bt.owenyang.top/hook?access_key=${{ secrets.HOOK_TOKEN }}&param=notion-next-blog
